[package]
name = "const_fn_assert"
version = "0.1.0"
authors = ["Nicolas Poelen <powlpy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
